# Generated by Django 3.1.5 on 2021-02-22 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('postId', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=128)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=128)),
                ('sender', models.CharField(max_length=128)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('object', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('source', models.TextField(default='')),
                ('origin', models.TextField(default='')),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends')], max_length=32)),
                ('unlisted', models.BooleanField()),
                ('author', models.TextField(default='')),
                ('contentType', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True)),
                ('categories', models.JSONField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('commentLink', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=32)),
                ('host', models.TextField()),
                ('url', models.TextField()),
                ('github', models.CharField(max_length=128)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
