# Generated by Django 3.1.5 on 2021-02-21 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.TextField(),
        ),
    ]
