# Generated by Django 3.1.5 on 2021-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
