# Generated by Django 3.1.5 on 2021-03-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')]),
        ),
    ]
