# Generated by Django 3.1.5 on 2021-03-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.JSONField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.author')),
            ],
        ),
    ]
