# Generated by Django 3.1.5 on 2021-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210221_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
