# Generated by Django 3.1.5 on 2021-02-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210224_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='receiver',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='sender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.TextField(choices=[('Public', 'Public'), ('Friends', 'Friends')]),
        ),
    ]
