# Generated by Django 3.1.6 on 2021-02-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210205_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=128, unique=True)),
                ('origin', models.CharField(max_length=128, unique=True)),
                ('visibility', models.CharField(choices=[('P', 'Public'), ('F', 'Friends')], max_length=32, unique=True)),
                ('unlisted', models.BooleanField()),
                ('isPrivateToFriends', models.BooleanField()),
                ('author', models.JSONField()),
                ('contentType', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField(blank=True)),
                ('categories', models.JSONField()),
                ('published', models.TimeField()),
                ('count', models.IntegerField()),
                ('pageSize', models.IntegerField(default=50)),
                ('commentLink', models.CharField(max_length=128)),
                ('comments', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
