# Generated by Django 3.1.5 on 2021-02-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210221_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pageSize',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='commentLink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
