# Generated by Django 3.1.5 on 2021-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210407_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
