# Generated by Django 3.1.6 on 2021-02-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20210206_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.TimeField(default='2021-02-06T02:09:54.107153'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('P', 'Public'), ('F', 'Friends')], max_length=32),
        ),
    ]
