# Generated by Django 3.1.5 on 2021-03-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20210315_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='approved',
        ),
        migrations.AlterField(
            model_name='follow',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.author'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='sender',
            field=models.JSONField(),
        ),
    ]
