# Generated by Django 3.1.6 on 2021-02-06 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20210206_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
