# Generated by Django 3.1.5 on 2021-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20210319_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='context',
        ),
        migrations.RemoveField(
            model_name='like',
            name='summary',
        ),
    ]
