# Generated by Django 3.1.5 on 2021-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20210206_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='_id',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
