# Generated by Django 3.1.5 on 2021-02-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20210206_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends')], max_length=32),
        ),
    ]
