# Generated by Django 3.1.6 on 2021-02-08 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20210206_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=128, unique=True)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=128)),
                ('published', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
