# Generated by Django 3.1.6 on 2021-02-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.CharField(default=9, max_length=128),
            preserve_default=False,
        ),
    ]
