# Generated by Django 3.1.6 on 2021-02-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_auto_20210208_0102'),
        ('quickstart', '0016_auto_20210208_0052'),
    ]

    operations = [
    ]
