# Generated by Django 3.1.5 on 2021-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_merge_20210208_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('_object', models.CharField(max_length=128)),
            ],
        ),
    ]
