# Generated by Django 3.1.5 on 2021-02-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20210216_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, unique=True)),
                ('items', models.JSONField()),
            ],
        ),
    ]
