# Generated by Django 3.1.5 on 2021-02-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20210215_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
