# Generated by Django 3.1.5 on 2021-02-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_like'),
        ('quickstart', '0019_auto_20210215_2214'),
    ]

    operations = [
    ]
