# Generated by Django 3.1.5 on 2021-02-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_merge_20210216_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
