# Generated by Django 3.1.5 on 2021-02-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20210215_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_id',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
