# Generated by Django 3.1.5 on 2021-02-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_auto_20210216_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='id',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
