# Generated by Django 3.1.5 on 2021-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_auto_20210220_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
