# Generated by Django 3.1.5 on 2021-02-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_auto_20210220_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='_object',
            new_name='object',
        ),
    ]
