# Generated by Django 3.1.5 on 2021-02-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_auto_20210220_2355'),
        ('quickstart', '0025_auto_20210221_0019'),
        ('quickstart', '0025_auto_20210221_0011'),
    ]

    operations = [
    ]
